version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    # 直接使用默认配置，不设置密码
    command: ["redis-server"]

volumes:
  redis_data:
